### ISSUE TITLE
UnityのAPIドキュメントが生成されない

### ISSUE THREAD

**Issue by hirohiroj3cub** [Studio-id-Game/MimiClean#79]
# 状態
- Unity関連のAPIReferenceがDocFxによって生成されない。

# 原因
- .slnが生成されていない

# 解決方法
- .slnを生成する
```
using UnityEditor;
using UnityEditor.Compilation;

public class SlnGenerator
{
    [MenuItem("Tools/Generate Solution")]
    public static void GenerateSolution()
    {
        CompilationPipeline.GenerateCSProjectFiles();
    }
}
```

- CI/CD
```
jobs:
  generate-sln:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v3
        with:
          unityVersion: 2022.3.10f1

      - name: Generate .sln and .csproj
        uses: game-ci/unity-actions/cli@v3
        with:
          args: -batchmode -nographics -quit -projectPath . -executeMethod SlnGenerator.GenerateSolution
```

(上記コードはChatGPTで生成したので、細かい所はチェック＆修正の必要あり)

# 参考
- https://github.com/NormandErwan/DocFxForUnity
  (このリポジトリでも、同じ理由によりドキュメントは生成できなかった。しかし、色々参考にはなりそう)
